language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build -t udagram-api-feed:v1.0 ./udagram-api-feed

  - docker build -t udagram-api-user:v1.0 ./udagram-api-user

  - docker build -t udagram-frontend:v1.0 ./udagram-frontend

  - docker build -t reverseproxy:v1.0 ./udagram-reverseproxy

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push chinhnv8/udagram-api-feed:v1.0
  - docker push chinhnv8/udagram-api-user:v1.0
  - docker push chinhnv8/udagram-frontend:v1.0
  - docker push chinhnv8/reverseproxy:v1.0    